let myAPI = [
    {
        id: 1,
        Title: 'BBQ Даблчизбургер',
        Desc: 'Говяжья котлета, помидоры, айсберг, сыр, соленые огурцы, лук, горчица, кетчуп, майонез',
        Cost: '42000 som',
        category: 'Burger',
        Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_2_ijWsv1G.png&w=256&q=75'
    },
    {
        id: 2,
        Title: 'Чикенбургер с сыром',
        Desc: 'Куриная котлета с сыром внутри, помидоры, айсберг, соленые огурцы, лук, кетчуп, майонез',
        Cost: '30000 som',
        category: 'Burger',
        Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_11_FRpFcQS_URlBQ7I.png&w=256&q=75',
    },
    {
        id: 3,
        Title: 'Мини BBQ даблчизбургер',
        Desc: 'Говяжья котлета, помидоры, айсберг, сыр, соленые огурцы, лук, горчица, кетчуп, майонез',
        Cost: '33000 som',
        category: 'Burger',
        Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_11_FRpFcQS_URlBQ7I_Q6fJZmm.png&w=256&q=75',
    },
    {
        id: 4,
        Title: 'BBQ Даблбургер',
        Desc: 'Говяжья котлета, помидоры, айсберг, соленые огурцы, лук, горчица, кетчуп, майонез',
        Cost: '39000 som',
        category: 'Burger',
        Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_19_9uQmIW4.png&w=256&q=75',
    },
    // {
    //     id: 5,
    //     Title: 'ББК Бургер с Соусом',
    //     Desc: '',
    //     Cost: '35000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2F%25D0%2591%25D0%2591%25D0%259A_%25D0%2591%25D1%2583%25D1%2580%25D0%25B3%25D0%25B5%25D1%2580_%25D1%2581_%25D1%2581%25D0%25BE%25D1%2583%25D1%2581%25D0%25BE%25D0%25BC_%25D0%2591%25D0%2591%25D0%259A.png&w=256&q=75',
    // },
    // {
    //     id: 6,
    //     Title: 'Чикензингер с сыром',
    //     Desc: 'Куриная грудинка, сыр, айсберг, соленые огурцы, помидор, кетчуп, майонез',
    //     Cost: '31000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_11_GqTWXpa_ZK9T5uj.png&w=256&q=75',
    // },
    // {
    //     id: 7,
    //     Title: 'Лонг аппер говяжий',
    //     Desc: 'Говяжья котлета, помидоры, айсберг, соленые огурцы, лук, горчица, кетчуп, майонез',
    //     Cost: '38000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_25_zVlBkTY.png&w=256&q=75',
    // },
    // {
    //     id: 8,
    //     Title: 'Лонг аппер курин',
    //     Desc: 'Куриная котлета с сыром, помидоры, айсберг, соленые огурцы, лук, кетчуп, майонез',
    //     Cost: '31000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_27_UheGgHK.png&w=256&q=75',
    // },
    // {
    //     id: 9,
    //     Title: 'Мини BBQ чизбургер',
    //     Desc: 'Говяжья котлета, помидоры, айсберг, сыр, соленые огурцы, лук, горчица, кетчуп, майонез',
    //     Cost: '23000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_28_JCgXGDf.png&w=256&q=75',
    // },
    // {
    //     id: 10,
    //     Title: 'BBQ Чизбургер',
    //     Desc: 'Говяжья котлета, помидоры, айсберг, сыр, соленые огурцы, лук, горчица, кетчуп, майонез',
    //     Cost: '35000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_42_9lzpTt0.png&w=256&q=75',
    // },
    // {
    //     id: 11,
    //     Title: 'BBQ Бургер',
    //     Desc: 'Говяжья котлета, помидоры, айсберг, соленые огурцы, лук, горчица, кетчуп, майонез',
    //     Cost: '32000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_46_83mKdU4.png&w=256&q=75',
    // },
    // {
    //     id: 12,
    //     Title: 'Чикензингер',
    //     Desc: 'Куриная грудинка, айсберг, соленые огурцы, помидор, кетчуп, майонез',
    //     Cost: '28000 som',
    //     category: 'Burger',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_46_83mKdU4.png&w=256&q=75',
    // },
    // {
    //     id: 13,
    //     Title: 'BBQ Лаваш (говяжий)',
    //     Desc: 'КуринГовяжье мясо, айсберг, лук, соленые огурцы, помидор, майонез, барбекю соус',
    //     Cost: '28000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_50_KkkYmcQ.png&w=256&q=75',
    // },
    // {
    //     id: 14,
    //     Title: 'Мини лаваш куриный',
    //     Desc: 'Куриная грудинка, помидор, соленые огурцы, майонез, соус',
    //     Cost: '21000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fbbq2_FOwzDRR_WK8OXKm.png&w=256&q=75',
    // },
    // {
    //     id: 15,
    //     Title: 'Мини лаваш',
    //     Desc: 'Говяжье мясо, помидор, чипсы, майонез, соус',
    //     Cost: '21000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_13_QEkJREE_NgDNZfX.png&w=256&q=75',
    // },
    // {
    //     id: 16,
    //     Title: 'Лаваш говяжий',
    //     Desc: 'Говяжье мясо, помидор, чипсы, майонез, соус',
    //     Cost: '33000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_13_Mje3zPS_3c2IvuV.png&w=256&q=75',
    // },
    // {
    //     id: 17,
    //     Title: 'Лаваш куринный',
    //     Desc: 'Куриная грудинка, помидор, соленые огурцы, майонез, соус',
    //     Cost: '33000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_13_Mje3zPS_3c2IvuV.png&w=256&q=75',
    // },
    // {
    //     id: 18,
    //     Title: 'Ок Лаваш Сырли',
    //     Desc: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_13_CndIZWX.png&w=256&q=75',
    //     Cost: '36000 som',
    //     category: 'Lavash',
    //     Img: '',
    // },
    // {
    //     id: 19,
    //     Title: 'Мини лаваш куриний с сыром',
    //     Desc: 'Куриная грудинка, помидор, сыр, соленые огурцы, майонез, соус',
    //     Cost: '24000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_20_hkxPgYP.png&w=256&q=75',
    // },
    // {
    //     id: 20,
    //     Title: 'BBQ Лаваш (котлет)',
    //     Desc: 'Говяжья котлета, айсберг, лук, соленые огурцы, помидор, майонез, барбекю соус, горчица',
    //     Cost: '28000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Flvsh.png&w=256&q=75',
    // },
    // {
    //     id: 21,
    //     Title: 'Ок Лаваш',
    //     Desc: '',
    //     Cost: '33000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_23_3lGHxb5.png&w=256&q=75',
    // },
    // {
    //     id: 22,
    //     Title: 'Мини лаваш с сыром',
    //     Desc: 'Говяжье мясо, помидор, чипсы, сыр, майонез, соус',
    //     Cost: '24000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fbbq1_fbtvN2g.png&w=256&q=75',
    // },
    // {
    //     id: 23,
    //     Title: 'Лаваш куринный с сыром',
    //     Desc: 'Куриная грудинка, помидор, сыр, соленые огурцы, майонез, соус',
    //     Cost: '36000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_23_3lGHxb5.png&w=256&q=75',
    // },
    // {
    //     id: 24,
    //     Title: 'Лаваш говяжий с сыром',
    //     Desc: 'Говяжье мясо, помидор, чипсы, сыр, майонез, соус',
    //     Cost: '36000 som',
    //     category: 'Lavash',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fbbq1_fbtvN2g.png&w=256&q=75',
    // },
    // {
    //     id: 25,
    //     Title: 'Донар',
    //     Desc: 'Говяжье мясо, помидоры, салатные листья, лук, соус',
    //     Cost: '31000 som',
    //     category: 'Donar',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_7_wVPPNny_BYf6jCp.png&w=256&q=75',
    // },
    // {
    //     id: 26,
    //     Title: 'Биг донар',
    //     Desc: 'Говяжье мясо, огурцы, салатные листья, лук, майонез, соус, сыр',
    //     Cost: '38000 som',
    //     category: 'Donar',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2F%25D0%259E%25D0%259A_%25D0%25BB%25D0%25B0%25D0%25B2%25D0%25B0%25D1%2588.png&w=256&q=75',
    // },
    // {
    //     id: 27,
    //     Title: 'Кинг-дог',
    //     Desc: 'Говяжье мясо, огурцы, салатные листья, лук, майонез, соус, сыр',
    //     Cost: '38000 som',
    //     category: 'Xot-Dog',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fhotdog_yxJryYN_MdOU9k5.png&w=256&q=75',
    // },
    // {
    //     id: 28,
    //     Title: 'Хот-дог',
    //     Desc: 'Канадская сосиска, соленые огурцы, помидор, салатные листья, кетчуп горчица',
    //     Cost: '22000 som',
    //     category: 'Xot-Dog',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fhotdog1_LI0FiPj.png&w=256&q=75',
    // },
    // {
    //     id: 29,
    //     Title: 'Хот дог мини',
    //     Desc: '',
    //     Cost: '12000 som',
    //     category: 'Xot-Dog',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2F%25D0%25A5%25D0%25BE%25D1%2582_%25D0%25B4%25D0%25BE%25D0%25B3.png&w=256&q=75',
    // },
    // {
    //     id: 30,
    //     Title: 'Хот-дог обыч',
    //     Desc: '',
    //     Cost: '19000 som',
    //     category: 'Xot-Dog',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2F%25D0%25A5%25D0%25BE%25D1%2582_%25D0%25B4%25D0%25BE%25D0%25B3_%25D0%25BC%25D0%25B8%25D0%25BD%25D0%25B8.png&w=256&q=75',
    // },
    // {
    //     id: 31,
    //     Title: 'Клаб сендвич',
    //     Desc: 'Куриная грудка, соленые огурцы, помидор, салатные листья, сыр, майонез, фри',
    //     Cost: '33000 som',
    //     category: 'sendwich',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fklab_JbXnCes_udeV9rp.png&w=256&q=75',
    // },
    // {
    //     id: 32,
    //     Title: 'Feed Up пица',
    //     Desc: 'Тесто, соус, сыр, сыр хохланд, говяжье мясо',
    //     Cost: '71000  som',
    //     category: 'Pizza',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fpizza_QA42Q5D_cFILYad.png&w=256&q=75',
    // },
    // {
    //     id: 33,
    //     Title: 'Пепперони пица',
    //     Desc: 'Тесто, соус, сыр, колбаса',
    //     Cost: '65000 som',
    //     category: 'Pizza',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_21_5rexohG.png&w=256&q=75',
    // },
    // {
    //     id: 34,
    //     Title: 'Барбекю пица',
    //     Desc: '',
    //     Cost: '6500 som',
    //     category: 'Pizza',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_51_0nOzl4g.png&w=256&q=75',
    // }, 
    // {
    //     id: 35,
    //     Title: 'ББК Курица',
    //     Desc: '',
    //     Cost: '32000 som',
    //     category: 'Garniri',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2F%25D0%2591%25D0%2591%25D0%259A_%25D0%25BA%25D1%2583%25D1%2580%25D0%25B8%25D1%2586%25D0%25B0.png&w=256&q=75',
    // }, 
    // {
    //     id: 36,
    //     Title: 'Наггетцы',
    //     Desc: '',
    //     Cost: '20000 som',
    //     category: 'Garniri',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fpr.png&w=256&q=75',
    // }, 
    // {
    //     id: 37,
    //     Title: 'Чикен Стикс',
    //     Desc: '',
    //     Cost: '22000 som',
    //     category: 'Garniri',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_36_O6sxRQg.png&w=256&q=75',
    // }, 
    // {
    //     id: 38,
    //     Title: 'Картофель по-деревенски',
    //     Desc: '',
    //     Cost: '18000 som',
    //     category: 'Garniri',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_1_2abkmV4_uuk7937.png&w=256&q=75',
    // }, 
    // {
    //     id: 39,
    //     Title: 'Попс',
    //     Desc: '',
    //     Cost: '19000 som',
    //     category: 'Garniri',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_40_Tmf2leu.png&w=256&q=75',
    // }, 
    // {
    //     id: 40,
    //     Title: 'Картофель фри',
    //     Desc: '',
    //     Cost: '16000 som',
    //     category: 'Garniri',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_41_5E6SZgG.png&w=256&q=75',
    // }, 
    // {
    //     id: 41,
    //     Title: 'Сырные кубики',
    //     Desc: '',
    //     Cost: '21000 som',
    //     category: 'Garniri',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2F2024-06-04_11.40.40.jpg&w=256&q=75',
    // }, 
    // {
    //     id: 42,
    //     Title: 'СПЕЦ ПРЕДЛОЖЕНИЕ (ББК ЛАВАШ КОТЛЕТ) КОМБО',
    //     Desc: 'BBQ Лаваш-Котлета, картофельные попсы, кола 0,4л, сырный соус',
    //     Cost: '58000 som',
    //     category: 'Kombo',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fbbq_kombo_H9mEzx1_kMXvPIr.png&w=256&q=75',
    // }, 
    // {
    //     id: 43,
    //     Title: 'Комбо№2 "ББК Бургер',
    //     Desc: 'BBQ Бургер, картофель фри, айсти, соус кетчуп',
    //     Cost: '69000 som',
    //     category: 'Kombo',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2F2024-06-04_12.38.57_8LXoikg.jpg&w=256&q=75',
    // }, 
    // {
    //     id: 44,
    //     Title: 'Комбо№1 "Лаваш"',
    //     Desc: 'Говяжий лаваш, картофель фри, кола 0,4л, соус кетчуп',
    //     Cost: '60000 som',
    //     category: 'Kombo',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_31_pDX1zzZ.png&w=256&q=75',
    // }, 
    // {
    //     id: 45,
    //     Title: 'Комбо№4 "Хотдог',
    //     Desc: 'Хот-дог, картофель по деревенски, кофе 3в1, сырный соус',
    //     Cost: '50000 som',
    //     category: 'Kombo',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2FImg_31_pDX1zzZ.png&w=256&q=75',
    // }, 
    // {
    //     id: 46,
    //     Title: 'Мехмон сет',
    //     Desc: '',
    //     Cost: '146500 som',
    //     category: 'Kombo',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fmehmon_set_f6Yx3Sk.png&w=256&q=75',
    // }, 
    // {
    //     id: 47,
    //     Title: 'СПЕЦ ПРЕДЛОЖЕНИЕ (ББКЛАВАШ МЯСО)КОМБО',
    //     Desc: 'BBQ Лаваш-Донар, картофельные попсы, кола 0,4л, сырный соус',
    //     Cost: '58000 som',
    //     category: 'Kombo',
    //     Img: 'https://feedup.uz/_next/image?url=https%3A%2F%2Fapi.feedup.uz%2Fmedia%2Fproducts%2Fbbq_kombo_79pcRxv_HqmEGfT.png&w=256&q=75',
    // }, 
    // {
    //     id: 48,
    //     Title: 'Комбо№3 ББК Даблбургер',
    //     Desc: '',
    //     Cost: '67000 som',
    //     category: 'Kombo',
    //     Img: '',
    // }, 
    // {
    //     id: 49,
    //     Title: 'Кидс "Комбо"',
    //     Desc: 'BBQ Мини чизбургер, картофельные попсы, сок Деназаврик, игрушка',
    //     Cost: '59000 som',
    //     category: 'Kombo',
    //     Img: '',
    // }, 
    // {
    //     id: 50,
    //     Title: 'Халапеньо 8гр',
    //     Desc: '',
    //     Cost: '3000 som',
    //     category: 'Kombo',
    //     Img: '',
    // }, 
    // {
    //     id: 51,
    //     Title: 'Кукиз',
    //     Desc: '',
    //     Cost: '7000 som',
    //     category: 'Kombo',
    //     Img: '',
    // }, 
    // {
    //     id: 52,
    //     Title: 'HEINZ честночный соус',
    //     Desc: '',
    //     Cost: '4000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // }, 
    // {
    //     id: 53,
    //     Title: 'Сыр (Hochland) шт',
    //     Desc: '',
    //     Cost: '3000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // }, 
    // {
    //     id: 54,
    //     Title: 'Мороженое',
    //     Desc: '',
    //     Cost: '8000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // }, 
    // {
    //     id: 55,
    //     Title: 'HEINZ кетчуп',
    //     Desc: '',
    //     Cost: '4000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // }, 
    // {
    //     id: 56,
    //     Title: 'Heinz BBQ соус',
    //     Desc: '',
    //     Cost: '4000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // }, 
    // {
    //     id: 57,
    //     Title: 'Стакан',
    //     Desc: '',
    //     Cost: '1000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // }, 
    // {
    //     id: 58,
    //     Title: 'HEINZ сырный соус',
    //     Desc: '',
    //     Cost: '4000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // }, 
    // {
    //     id: 59,
    //     Title: 'Халапеньо 16rр',
    //     Desc: '',
    //     Cost: '4000 som',
    //     category: 'dopolnitelno',
    //     Img: '',
    // },  
    // {
    //     id: 60,
    //     Title: 'Чай черный',
    //     Desc: '',
    //     Cost: '5000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 61,
    //     Title: 'Разлив Кока кола 500мл',
    //     Desc: '',
    //     Cost: '10000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 62,
    //     Title: 'Лимонад"Маракуя"',
    //     Desc: '',
    //     Cost: '16000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 63,
    //     Title: 'Чай черный с limonom',
    //     Desc: '',
    //     Cost: '6000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 64,
    //     Title: 'Вода без газ 0,5л',
    //     Desc: '',
    //     Cost: '3000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 65,
    //     Title: 'Разлив фанта 500мл',
    //     Desc: '',
    //     Cost: '10000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 66,
    //     Title: 'Чай зеленый',
    //     Desc: '',
    //     Cost: '4000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 67,
    //     Title: 'coca-cola 0,5л',
    //     Desc: '',
    //     Cost: '10000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 68,
    //     Title: 'Лимонад"Ягода"',
    //     Desc: '',
    //     Cost: '16000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 69,
    //     Title: 'Айсти',
    //     Desc: '',
    //     Cost: '22000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 70,
    //     Title: 'Разлив фанта 400мл',
    //     Desc: '',
    //     Cost: '9000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 71,
    //     Title: 'ДенаЗаврик сок',
    //     Desc: '',
    //     Cost: '3000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 72,
    //     Title: 'Лимонад"Клубничный',
    //     Desc: '',
    //     Cost: '16000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 73,
    //     Title: 'Разлив Кока кола 400мл',
    //     Desc: '',
    //     Cost: '9000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 74,
    //     Title: 'Дена 0,33',
    //     Desc: '0,33 gr',
    //     Cost: '8000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 75,
    //     Title: 'coca-cola 1,5',
    //     Desc: '',
    //     Cost: '20000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 76,
    //     Title: 'Лимонад"Мохито"',
    //     Desc: '',
    //     Cost: '16000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 77,
    //     Title: 'fanta 1,5л',
    //     Desc: '',
    //     Cost: '20000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 78,
    //     Title: 'fanta 0,5л',
    //     Desc: '',
    //     Cost: '10000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 79,
    //     Title: 'Разлив спрайт 500мл',
    //     Desc: '',
    //     Cost: '10000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 80,
    //     Title: 'Чай с limonom зеленый',
    //     Desc: '',
    //     Cost: '6000 som',
    //     category: 'napitki',
    //     Img: '',
    // },  
    // {
    //     id: 81,
    //     Title: 'Цезарь',
    //     Desc: '',
    //     Cost: '26000 som',
    //     category: 'salati',
    //     Img: '',
    // },  
]


export default myAPI
